#SPDX-License-Identifier: MIT-0
---
# tasks file for rhel_kickstart
- name: Calling rhel_kickstart.yml file.
  include_tasks:
    file: rhel_kickstart.yml
  when: ansible_facts['os_family'] == 'RedHat' or ansible_facts['distribution'] == 'CentOS'

- name: Calling ubuntu_kickstart.yml file.
  include_tasks:
    file: ubuntu_kickstart.yml
  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'